### ISSUE TITLE
issue when parsing loop segments

### ISSUE THREAD

**Issue by dnbhatt1991** [mvogttech/node-x12-edi#1]
hello my input is 855 edi file i am not able parse Po1 segment 
ISA*00*          *00*          *ZZ*SENDERID       *ZZ*RECEIVERID     *230920*1300*U*00401*000000002*0*P*>
GS*PR*SENDERID*RECEIVERID*20230920*1300*2*X*004010
ST*855*0002
BAK*00*AC*PO654321*20230920
REF*VR*VENDOR9876
N1*ST*Warehouse A*92*WHSE123
N3*789 Warehouse Rd
N4*New York*NY*10001
N1*BT*Head Office*92*OFF456
N3*101 HQ Ave
N4*Boston*MA*02108
PO1*1*200*EA*15.00**IN*23456*VN*VendorItem789*BP*BuyerPart789
PID*F****Red Widgets
PO1*2*150*EA*25.00**IN*34567*VN*VendorItem101*BP*BuyerPart101
PID*F****Blue Gadgets
CTT*2
SE*15*0002
GE*1*2
IEA*1*000000002

map segment configured like 
 detail: {
      items: new LoopMap({
        position: 0,
        values: {
          item: Object.assign.apply(
            {},
            PO1_ELEMENTS.map((element, index) => {
              return {
                [element]: new FieldMap({
                  segmentIdentifier: "PO1",
                  identifierValue: null,
                  identifierPosition: null,
                  valuePosition: index,
                }),
              };
            })
          )        
        },
      }),
    }  
    but recived this error
    Failed to read file: Cannot read properties of undefined (reading 'content')

**Comment by mvogttech** [comment]
Try using a reduce rather than Object.assign.apply method. Such as

`detail: {
    items: new LoopMap({
        position: 0,
        values: {
            item: PO1_ELEMENTS.reduce((acc, element, index) => {
                acc[element] = new FieldMap({
                    segmentIdentifier: "PO1",
                    identifierValue: null,
                    identifierPosition: null,
                    valuePosition: index,
                });
                return acc;
            }, {})
        }
    })
}`

**Comment by mvogttech** [comment]
Can you please provide the full map object you're using.

**Comment by mvogttech** [comment]
I believe it is because your input is missing the segment seperator such as `*`

`
 ISA*00* *00* *ZZ*111111111 *01*007911209
 *150129*2215*U*00401*000122406*0*P*>~
 GS*PR*111111111*007911209*20150129*2215*3152*X*004010~
 ST*855*3152~
 BAK*00*AC*801222*20150129~
 PO1*1*140*******UP*893647*VP*EXPI9301CTBLK*BP*999999999999 ~
 ACK*IA*****010*20150205~
 CTT*1~
 SE*10*3152~
 GE*1*3152~
 IEA*1*000122406
`
